/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiReviewRouteImport } from './routes/ai-review'
import { Route as AiWorkspaceRouteImport } from './routes/ai-workspace'
import { Route as AmlRouteImport } from './routes/aml'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OversightRouteImport } from './routes/oversight'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsOnboardingRouteImport } from './routes/clients.onboarding'
import { Route as ProposalsProposalIdRouteImport } from './routes/proposals.$proposalId'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as ServicesCreateRouteImport } from './routes/services/create'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as TasksCreateRouteImport } from './routes/tasks.create'
import { Route as ServicesPackagesPackageIdRouteImport } from './routes/services/packages/$packageId'
import { Route as ServicesPackagesCreateRouteImport } from './routes/services/packages/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReviewRoute = AiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceRoute = AiWorkspaceRouteImport.update({
  id: '/ai-workspace',
  path: '/ai-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlRoute = AmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OversightRoute = OversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsOnboardingRoute = ClientsOnboardingRouteImport.update({
  id: '/clients/onboarding',
  path: '/clients/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsProposalIdRoute = ProposalsProposalIdRouteImport.update({
  id: '/$proposalId',
  path: '/$proposalId',
  getParentRoute: () => ProposalsRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreateRoute = ServicesCreateRouteImport.update({
  id: '/services/create',
  path: '/services/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPackagesPackageIdRoute =
  ServicesPackagesPackageIdRouteImport.update({
    id: '/services/packages/$packageId',
    path: '/services/packages/$packageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPackagesCreateRoute = ServicesPackagesCreateRouteImport.update({
  id: '/services/packages/create',
  path: '/services/packages/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-review': typeof AiReviewRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/aml': typeof AmlRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/oversight': typeof OversightRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/onboarding': typeof ClientsOnboardingRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/create': typeof ServicesCreateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/clients/': typeof ClientsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/services/packages/$packageId': typeof ServicesPackagesPackageIdRoute
  '/services/packages/create': typeof ServicesPackagesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-review': typeof AiReviewRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/aml': typeof AmlRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/oversight': typeof OversightRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/onboarding': typeof ClientsOnboardingRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/create': typeof ServicesCreateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/clients': typeof ClientsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/services/packages/$packageId': typeof ServicesPackagesPackageIdRoute
  '/services/packages/create': typeof ServicesPackagesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-review': typeof AiReviewRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/aml': typeof AmlRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/oversight': typeof OversightRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/onboarding': typeof ClientsOnboardingRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/create': typeof ServicesCreateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/clients/': typeof ClientsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/services/packages/$packageId': typeof ServicesPackagesPackageIdRoute
  '/services/packages/create': typeof ServicesPackagesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-review'
    | '/ai-workspace'
    | '/aml'
    | '/communications'
    | '/dashboard'
    | '/help'
    | '/insights'
    | '/login'
    | '/onboarding'
    | '/oversight'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/clients/$clientId'
    | '/clients/onboarding'
    | '/proposals/$proposalId'
    | '/services/$serviceId'
    | '/services/create'
    | '/staff/$staffId'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/clients/'
    | '/services/'
    | '/tasks/'
    | '/services/packages/$packageId'
    | '/services/packages/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-review'
    | '/ai-workspace'
    | '/aml'
    | '/communications'
    | '/dashboard'
    | '/help'
    | '/insights'
    | '/login'
    | '/onboarding'
    | '/oversight'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/clients/$clientId'
    | '/clients/onboarding'
    | '/proposals/$proposalId'
    | '/services/$serviceId'
    | '/services/create'
    | '/staff/$staffId'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/clients'
    | '/services'
    | '/tasks'
    | '/services/packages/$packageId'
    | '/services/packages/create'
  id:
    | '__root__'
    | '/'
    | '/ai-review'
    | '/ai-workspace'
    | '/aml'
    | '/communications'
    | '/dashboard'
    | '/help'
    | '/insights'
    | '/login'
    | '/onboarding'
    | '/oversight'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/clients/$clientId'
    | '/clients/onboarding'
    | '/proposals/$proposalId'
    | '/services/$serviceId'
    | '/services/create'
    | '/staff/$staffId'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/clients/'
    | '/services/'
    | '/tasks/'
    | '/services/packages/$packageId'
    | '/services/packages/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReviewRoute: typeof AiReviewRoute
  AiWorkspaceRoute: typeof AiWorkspaceRoute
  AmlRoute: typeof AmlRoute
  CommunicationsRoute: typeof CommunicationsRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OversightRoute: typeof OversightRoute
  ProposalsRoute: typeof ProposalsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsOnboardingRoute: typeof ClientsOnboardingRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesCreateRoute: typeof ServicesCreateRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCreateRoute: typeof TasksCreateRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ServicesPackagesPackageIdRoute: typeof ServicesPackagesPackageIdRoute
  ServicesPackagesCreateRoute: typeof ServicesPackagesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-review': {
      id: '/ai-review'
      path: '/ai-review'
      fullPath: '/ai-review'
      preLoaderRoute: typeof AiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace': {
      id: '/ai-workspace'
      path: '/ai-workspace'
      fullPath: '/ai-workspace'
      preLoaderRoute: typeof AiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml': {
      id: '/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof AmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversight': {
      id: '/oversight'
      path: '/oversight'
      fullPath: '/oversight'
      preLoaderRoute: typeof OversightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/onboarding': {
      id: '/clients/onboarding'
      path: '/clients/onboarding'
      fullPath: '/clients/onboarding'
      preLoaderRoute: typeof ClientsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$proposalId': {
      id: '/proposals/$proposalId'
      path: '/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof ProposalsProposalIdRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/create': {
      id: '/services/create'
      path: '/services/create'
      fullPath: '/services/create'
      preLoaderRoute: typeof ServicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/packages/$packageId': {
      id: '/services/packages/$packageId'
      path: '/services/packages/$packageId'
      fullPath: '/services/packages/$packageId'
      preLoaderRoute: typeof ServicesPackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/packages/create': {
      id: '/services/packages/create'
      path: '/services/packages/create'
      fullPath: '/services/packages/create'
      preLoaderRoute: typeof ServicesPackagesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProposalsRouteChildren {
  ProposalsProposalIdRoute: typeof ProposalsProposalIdRoute
}

const ProposalsRouteChildren: ProposalsRouteChildren = {
  ProposalsProposalIdRoute: ProposalsProposalIdRoute,
}

const ProposalsRouteWithChildren = ProposalsRoute._addFileChildren(
  ProposalsRouteChildren,
)

interface StaffRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReviewRoute: AiReviewRoute,
  AiWorkspaceRoute: AiWorkspaceRoute,
  AmlRoute: AmlRoute,
  CommunicationsRoute: CommunicationsRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OversightRoute: OversightRoute,
  ProposalsRoute: ProposalsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsOnboardingRoute: ClientsOnboardingRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesCreateRoute: ServicesCreateRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCreateRoute: TasksCreateRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ServicesPackagesPackageIdRoute: ServicesPackagesPackageIdRoute,
  ServicesPackagesCreateRoute: ServicesPackagesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
